### ISSUE TITLE
options.variable + options.amd_wrapper

### ISSUE THREAD

**Issue by pecuchet** [adamdicarlo/grunt-twig#4]
Hi,
If I define a plain variable like `templates` to store the templates in combination with amd_wrapper, this variable is not declared: there is no `var`keyword. This leads to an undefined error in the logical OR.
Plus, wouldn't it be better if the amd wrapper were defined as a module effectively returning something?
Something like this:
```
define(["twig"], function(Twig) {
    var templates = templates || {};
    templates["project.html"] = Twig.twig({...});
    templates["home.html"] = Twig.twig({...});
    return templates; 
});
```

**Comment by ekyna** [comment]
+1 for the ability to use define(...)
```javascript 
define(['twig'], function(Twig) {
    var templates = {};
    // ...
    return templates;
});
```
